# Versi√≥n corregida para compatibilidad y evitar choque de puertos
version: '2.1'
services:
  postgresql:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=pacientesms
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      # Puerto externo 5433 para NO chocar con el Gateway
      - 127.0.0.1:5433:5432